### ISSUE TITLE
List of changes expected for frequent updates in ageless

### ISSUE THREAD

**Issue by ProditorMagnus** [Byteron/Millennium_Era#3]
Important changes
- [x] Unit type ids must not have spaces
- [x] Unit type ids need to have prefix that can be replaced to ageless prefix (so no commonly used string)
- [x] Identifier ME might be used for Mercenaries Era, though internally it should be MRC or mrc in most places
- [x] > # the actual code which makes the ability work is in the Millennium_Era/units/vampires.cfg file < ActionWML should be in utils or data folder

Nice to have
- [x] Use prefix for everything where possible - that is like: unit type id, race id, ability id, weapon special id, event id, variable name, movetype name, global (those not #undef-ed) macro name
- [x] Factions for rpg

Internal
- [x] Some units are included though units folder, others directly from main
- [x] You should remove {MAGENTA_IS_THE_TEAM_COLOR}
- [x] MOVEMENT_STONE_SLEEP event has no id

**Comment by Byteron** [comment]
I opened a branch 'ageless' which will be slightly different and optimized for you to handle updates.
I will also remove all default factions from AoE, default and RPG Era for ageless, in case you don't handle that automatically as well.
